RubyOnRails - TraversyMedia/simpleblog/config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: 'home'
  get 'about' => 'pages#about', as: 'about'
  resources :posts do
    resources :comments
  end
end

RubyOnRails - TraversyMedia/simpleblog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RubyOnRails - TraversyMedia/simpleblog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

RubyOnRails - TraversyMedia/simpleblog/app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    validates :title, presence: true, length: {minimum: 5}
end

RubyOnRails - TraversyMedia/simpleblog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

RubyOnRails - TraversyMedia/simpleblog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name: "wavoges", password: "123456", only: [:destroy]
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        redirect_to post_path(@post)
    end
    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end
    private
    def comment_params
        params.require(:comment).permit(:username, :body)
    end
end

RubyOnRails - TraversyMedia/simpleblog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @title = 'About Us'
        @content = 'This is the about page, meant for more information about this current app and where or how to get in contact with the creators.'
    end
end

RubyOnRails - TraversyMedia/simpleblog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    http_basic_authenticate_with name: "wavoges", password: "123456", except: [:index, :show]
    def index
        @posts = Post.all
    end
    def new
        @post = Post.new
    end
    def create
        @post = Post.new(post_params)
        if (@post.save)
            redirect_to @post
        else
            render 'new'
        end
    end
    def show
        @post = Post.find(params[:id])
    end
    def edit
        @post = Post.find(params[:id])
    end
    def update
        @post = Post.find(params[:id])
        if (@post.update(post_params))
            redirect_to @post
        else
            render 'edit'
        end
    end
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end
    private
    def post_params
        params.require(:post).permit(:title, :body)
    end
end

RubyOnRails - TraversyMedia/simpleblog/app/helpers/application_helper.rb
module ApplicationHelper
end

RubyOnRails - TraversyMedia/simpleblog/app/helpers/comments_helper.rb
module CommentsHelper
end

RubyOnRails - TraversyMedia/simpleblog/app/helpers/pages_helper.rb
module PagesHelper
end

RubyOnRails - TraversyMedia/simpleblog/app/helpers/posts_helper.rb
module PostsHelper
end

RubyOnRails - TraversyMedia/simpleblog/app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
    <div class="well">
        <p>
            <strong><%= comment.username %></strong>: <%= comment.body %><br>
            <%= link_to 'Delete Comment', [comment.post, comment], method: :delete, data: {confirm: 'Are you sure?'} %>
        </p>
    </div>
<% end %>

RubyOnRails - TraversyMedia/simpleblog/app/views/comments/_form.html.erb
<h3>Add A Comment</h3>
<%= form_for ([@post, @post.comments.build]) do |f| %>
    <p>
        <%= f.label :username %><br>
        <%= f.text_field(:username, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body, {:class => 'form=control'}) %>
    </p>
    <p>
        <%= f.submit({:class => 'btn btn-default'}) %>
    </p>
<% end %>

RubyOnRails - TraversyMedia/simpleblog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Simple Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse container" id="navbarSupportedContent">
        <ul class="navbar-nav row align-items-center">
          <li class="nav-item col">
            <%= link_to "Home", home_path %>
          </li>
        </ul>
        <ul class="navbar-nav row align-items-end">
          <li class="nav-item col">
            <%= link_to "Create Post", new_post_path %>
          </li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

RubyOnRails - TraversyMedia/simpleblog/app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

RubyOnRails - TraversyMedia/simpleblog/app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger">
                <%= msg %>
            </div>
        <% end %>
    <% end %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>
<% end %>

RubyOnRails - TraversyMedia/simpleblog/app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<% @posts.each do |post| %>
    <div class="well">
        <h3><%= post.title %></h3>
        <p><%= post.body %></p>
        <%= link_to "Read More", post_path(post), :class => 'btn btn-default' %>
    </div>
<% end %>

RubyOnRails - TraversyMedia/simpleblog/app/views/posts/new.html.erb
<h1>Add Post</h1>
<%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger">
                <%= msg %>
            </div>
        <% end %>
    <% end %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>
<% end %>

RubyOnRails - TraversyMedia/simpleblog/app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-default' %>
<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
<hr>
<%= render 'comments/comments' %>
<%= render 'comments/form' %>